/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form;

import javax.swing.*;
import java.awt.*;
import DataBaseConnection.DataBaseConnection;
import static form.frmLogin.getUsername;
//import static form.frmSearch.createListTtemAdded;
import java.sql.PreparedStatement;
import javax.swing.*;
import java.sql.ResultSet;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author NguyenCongHoan
 */
public class frmItemClient extends javax.swing.JFrame {
//	int countClicked = 0; // Đếm số lần click button Search

	frmSearch windowSearch;
	ArrayList<String> listItemName = new ArrayList<>();
	ArrayList<Integer> listPrice = new ArrayList<>();
	ArrayList<Integer> listAmount = new ArrayList<>();

	// Lưu tên sản phẩm ở dạng lower-case
	// sử dụng để tìm kiếm sản phẩm khi viết hoa hoặc không
	ArrayList<String> listItemNameLowerCase = new ArrayList<>();
	static Vector result = new Vector(); // Lưu kết quả tìm kiếm
	static Vector<Vector> listTtemAdded = new Vector<Vector>();
	int countItem1 = 0;
	int countItem2 = 0;
	int countItem3 = 0;
	int countItem4 = 0;
	int countItem5 = 0;
	int countItem6 = 0;

	/**
	 * Creates new form frmSanPham
	 */
	public frmItemClient() throws SQLException {
		initComponents();

		Connection cnt = null;
		PreparedStatement stm = null;
		try {
			cnt = DataBaseConnection.getConnection();
			String sql = "SELECT ten_san_pham, gia, so_luong FROM tbsanpham";
			stm = cnt.prepareStatement(sql);
			ResultSet rs = stm.executeQuery();

			while (rs.next()) {
				String itemName = rs.getString("ten_san_pham");
				listItemName.add(itemName);
				listPrice.add(rs.getInt("gia"));
				listAmount.add(rs.getInt("so_luong"));
				listItemNameLowerCase.add(itemName.toLowerCase());
			}

		} catch (ClassNotFoundException ex) {
			Logger.getLogger(frmItemClient.class.getName()).log(Level.SEVERE, null, ex);
		} finally {
			try {
				if (stm != null) {
					stm.close();
				}

				if (cnt != null) {
					cnt.close();
				}

			} catch (SQLException ex) {
				Logger.getLogger(frmLogin.class.getName()).log(Level.SEVERE, null, ex);
			}
		}
	}

	private void setResultVector(Vector result) {
		this.result = result;
	}

	public static Vector<String> getResultVector() {
		return result;
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnSearch = new javax.swing.JButton();
        tfSearch = new javax.swing.JTextField();
        btnCart = new javax.swing.JButton();
        Item1 = new javax.swing.JPanel();
        imgItem1 = new javax.swing.JLabel();
        lbHPrice1 = new javax.swing.JLabel();
        lbNameItem1 = new javax.swing.JLabel();
        lbPriceItem1 = new javax.swing.JLabel();
        lbHAmount1 = new javax.swing.JLabel();
        lbAmountItem1 = new javax.swing.JLabel();
        btnAdd1 = new javax.swing.JButton();
        btnShowAll = new javax.swing.JButton();
        Item2 = new javax.swing.JPanel();
        imgItem2 = new javax.swing.JLabel();
        lbHPrice2 = new javax.swing.JLabel();
        lbNameItem2 = new javax.swing.JLabel();
        lbPriceItem2 = new javax.swing.JLabel();
        lbHAmount2 = new javax.swing.JLabel();
        lbAmountItem2 = new javax.swing.JLabel();
        btnAdd2 = new javax.swing.JButton();
        Item3 = new javax.swing.JPanel();
        imgItem3 = new javax.swing.JLabel();
        lbHPrice3 = new javax.swing.JLabel();
        lbNameItem3 = new javax.swing.JLabel();
        lbPriceItem3 = new javax.swing.JLabel();
        lbHAmount3 = new javax.swing.JLabel();
        lbAmountItem3 = new javax.swing.JLabel();
        btnAdd3 = new javax.swing.JButton();
        Item4 = new javax.swing.JPanel();
        imgItem4 = new javax.swing.JLabel();
        lbHPrice4 = new javax.swing.JLabel();
        lbNameItem4 = new javax.swing.JLabel();
        lbPriceItem4 = new javax.swing.JLabel();
        lbHAmount4 = new javax.swing.JLabel();
        lbAmountItem4 = new javax.swing.JLabel();
        btnAdd4 = new javax.swing.JButton();
        Item5 = new javax.swing.JPanel();
        imgItem5 = new javax.swing.JLabel();
        lbHPrice5 = new javax.swing.JLabel();
        lbNameItem5 = new javax.swing.JLabel();
        lbPriceItem5 = new javax.swing.JLabel();
        lbHAmount5 = new javax.swing.JLabel();
        lbAmountItem5 = new javax.swing.JLabel();
        btnAdd5 = new javax.swing.JButton();
        Item6 = new javax.swing.JPanel();
        imgItem6 = new javax.swing.JLabel();
        lbHPrice6 = new javax.swing.JLabel();
        lbNameItem6 = new javax.swing.JLabel();
        lbPriceItem6 = new javax.swing.JLabel();
        lbHAmount6 = new javax.swing.JLabel();
        lbAmountItem6 = new javax.swing.JLabel();
        btnAdd6 = new javax.swing.JButton();
        btnProfile = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("WindowTrending");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        btnSearch.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Downloads\\search.png")); // NOI18N
        btnSearch.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        tfSearch.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        tfSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfSearchActionPerformed(evt);
            }
        });
        tfSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfSearchKeyPressed(evt);
            }
        });

        btnCart.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Downloads\\shopping (2).png")); // NOI18N
        btnCart.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        btnCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCartActionPerformed(evt);
            }
        });

        Item1.setBackground(new java.awt.Color(255, 255, 255));
        Item1.setMinimumSize(new java.awt.Dimension(178, 157));
        Item1.setPreferredSize(new java.awt.Dimension(178, 157));

        imgItem1.setBackground(new java.awt.Color(255, 255, 255));
        imgItem1.setMaximumSize(new java.awt.Dimension(100, 63));
        imgItem1.setMinimumSize(new java.awt.Dimension(100, 63));
        imgItem1.setPreferredSize(new java.awt.Dimension(100, 63));

        lbHPrice1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbHPrice1.setText("Giá:");

        lbNameItem1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbNameItem1.setText("Nike Jordan 1 Hyper Royal");

        lbPriceItem1.setText("Giá");

        lbHAmount1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbHAmount1.setText("Số lượng:");

        lbAmountItem1.setText("Số lượng");

        btnAdd1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Downloads\\add-to-cart (1).png")); // NOI18N
        btnAdd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdd1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Item1Layout = new javax.swing.GroupLayout(Item1);
        Item1.setLayout(Item1Layout);
        Item1Layout.setHorizontalGroup(
            Item1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Item1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Item1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Item1Layout.createSequentialGroup()
                        .addComponent(lbHPrice1)
                        .addGap(49, 49, 49)
                        .addComponent(lbPriceItem1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbNameItem1)
                    .addGroup(Item1Layout.createSequentialGroup()
                        .addComponent(lbHAmount1)
                        .addGap(18, 18, 18)
                        .addComponent(lbAmountItem1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(Item1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(imgItem1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22)
                .addComponent(btnAdd1)
                .addGap(14, 14, 14))
        );
        Item1Layout.setVerticalGroup(
            Item1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Item1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Item1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(imgItem1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdd1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbNameItem1)
                .addGap(8, 8, 8)
                .addGroup(Item1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbPriceItem1)
                    .addComponent(lbHPrice1, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Item1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbAmountItem1)
                    .addComponent(lbHAmount1))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        btnShowAll.setText("Hiển thị tất cả sản phẩm");
        btnShowAll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowAllActionPerformed(evt);
            }
        });

        Item2.setBackground(new java.awt.Color(255, 255, 255));
        Item2.setMinimumSize(new java.awt.Dimension(178, 157));

        imgItem2.setMaximumSize(new java.awt.Dimension(100, 63));
        imgItem2.setMinimumSize(new java.awt.Dimension(100, 63));
        imgItem2.setPreferredSize(new java.awt.Dimension(100, 63));

        lbHPrice2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbHPrice2.setText("Giá:");

        lbNameItem2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbNameItem2.setText("Adidas Yeezy 350V2 Clay");

        lbPriceItem2.setText("Giá");

        lbHAmount2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbHAmount2.setText("Số lượng:");

        lbAmountItem2.setText("Số lượng");

        btnAdd2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Downloads\\add-to-cart (1).png")); // NOI18N
        btnAdd2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdd2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Item2Layout = new javax.swing.GroupLayout(Item2);
        Item2.setLayout(Item2Layout);
        Item2Layout.setHorizontalGroup(
            Item2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Item2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Item2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Item2Layout.createSequentialGroup()
                        .addComponent(lbHPrice2)
                        .addGap(49, 49, 49)
                        .addComponent(lbPriceItem2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbNameItem2)
                    .addGroup(Item2Layout.createSequentialGroup()
                        .addComponent(lbHAmount2)
                        .addGap(18, 18, 18)
                        .addComponent(lbAmountItem2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(Item2Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(imgItem2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAdd2)
                .addGap(12, 12, 12))
        );
        Item2Layout.setVerticalGroup(
            Item2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Item2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Item2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(imgItem2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdd2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbNameItem2)
                .addGap(8, 8, 8)
                .addGroup(Item2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbHPrice2)
                    .addComponent(lbPriceItem2))
                .addGap(8, 8, 8)
                .addGroup(Item2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbAmountItem2)
                    .addComponent(lbHAmount2))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        Item3.setBackground(new java.awt.Color(255, 255, 255));
        Item3.setMinimumSize(new java.awt.Dimension(178, 157));

        imgItem3.setMaximumSize(new java.awt.Dimension(100, 63));
        imgItem3.setMinimumSize(new java.awt.Dimension(100, 63));
        imgItem3.setPreferredSize(new java.awt.Dimension(100, 63));

        lbHPrice3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbHPrice3.setText("Giá:");

        lbNameItem3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbNameItem3.setText("Nike Airforce 1 Travis");

        lbPriceItem3.setText("Giá");

        lbHAmount3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbHAmount3.setText("Số lượng:");

        lbAmountItem3.setText("Số lượng");

        btnAdd3.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Downloads\\add-to-cart (1).png")); // NOI18N
        btnAdd3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdd3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Item3Layout = new javax.swing.GroupLayout(Item3);
        Item3.setLayout(Item3Layout);
        Item3Layout.setHorizontalGroup(
            Item3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Item3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Item3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Item3Layout.createSequentialGroup()
                        .addComponent(lbHPrice3)
                        .addGap(49, 49, 49)
                        .addComponent(lbPriceItem3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbNameItem3)
                    .addGroup(Item3Layout.createSequentialGroup()
                        .addComponent(lbHAmount3)
                        .addGap(18, 18, 18)
                        .addComponent(lbAmountItem3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(Item3Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(imgItem3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAdd3)
                .addGap(12, 12, 12))
        );
        Item3Layout.setVerticalGroup(
            Item3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Item3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Item3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(imgItem3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdd3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbNameItem3)
                .addGap(8, 8, 8)
                .addGroup(Item3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbHPrice3)
                    .addComponent(lbPriceItem3))
                .addGap(8, 8, 8)
                .addGroup(Item3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbAmountItem3)
                    .addComponent(lbHAmount3))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        Item4.setBackground(new java.awt.Color(255, 255, 255));
        Item4.setMinimumSize(new java.awt.Dimension(178, 157));

        imgItem4.setMaximumSize(new java.awt.Dimension(100, 63));
        imgItem4.setMinimumSize(new java.awt.Dimension(100, 63));
        imgItem4.setPreferredSize(new java.awt.Dimension(100, 63));

        lbHPrice4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbHPrice4.setText("Giá:");

        lbNameItem4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbNameItem4.setText("Nike Jordan 4 Black");

        lbPriceItem4.setText("Giá");

        lbHAmount4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbHAmount4.setText("Số lượng:");

        lbAmountItem4.setText("Số lượng");

        btnAdd4.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Downloads\\add-to-cart (1).png")); // NOI18N
        btnAdd4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdd4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Item4Layout = new javax.swing.GroupLayout(Item4);
        Item4.setLayout(Item4Layout);
        Item4Layout.setHorizontalGroup(
            Item4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Item4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Item4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Item4Layout.createSequentialGroup()
                        .addComponent(lbHPrice4)
                        .addGap(49, 49, 49)
                        .addComponent(lbPriceItem4, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbNameItem4)
                    .addGroup(Item4Layout.createSequentialGroup()
                        .addComponent(lbHAmount4)
                        .addGap(18, 18, 18)
                        .addComponent(lbAmountItem4, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(Item4Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(imgItem4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAdd4)
                .addGap(12, 12, 12))
        );
        Item4Layout.setVerticalGroup(
            Item4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Item4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Item4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(imgItem4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdd4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbNameItem4)
                .addGap(8, 8, 8)
                .addGroup(Item4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbHPrice4)
                    .addComponent(lbPriceItem4))
                .addGap(8, 8, 8)
                .addGroup(Item4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbAmountItem4)
                    .addComponent(lbHAmount4))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        Item5.setBackground(new java.awt.Color(255, 255, 255));
        Item5.setMinimumSize(new java.awt.Dimension(178, 157));

        imgItem5.setMaximumSize(new java.awt.Dimension(100, 63));
        imgItem5.setMinimumSize(new java.awt.Dimension(100, 63));
        imgItem5.setPreferredSize(new java.awt.Dimension(100, 63));

        lbHPrice5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbHPrice5.setText("Giá:");

        lbNameItem5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbNameItem5.setText("Nike Jordan 1 Travis");

        lbPriceItem5.setText("Giá");

        lbHAmount5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbHAmount5.setText("Số lượng:");

        lbAmountItem5.setText("Số lượng");

        btnAdd5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Downloads\\add-to-cart (1).png")); // NOI18N
        btnAdd5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdd5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Item5Layout = new javax.swing.GroupLayout(Item5);
        Item5.setLayout(Item5Layout);
        Item5Layout.setHorizontalGroup(
            Item5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Item5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Item5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Item5Layout.createSequentialGroup()
                        .addComponent(lbHPrice5)
                        .addGap(49, 49, 49)
                        .addComponent(lbPriceItem5, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbNameItem5)
                    .addGroup(Item5Layout.createSequentialGroup()
                        .addComponent(lbHAmount5)
                        .addGap(18, 18, 18)
                        .addComponent(lbAmountItem5, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(Item5Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(imgItem5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAdd5)
                .addGap(12, 12, 12))
        );
        Item5Layout.setVerticalGroup(
            Item5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Item5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Item5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(imgItem5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdd5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbNameItem5)
                .addGap(8, 8, 8)
                .addGroup(Item5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbHPrice5)
                    .addComponent(lbPriceItem5))
                .addGap(8, 8, 8)
                .addGroup(Item5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbAmountItem5)
                    .addComponent(lbHAmount5))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        Item6.setBackground(new java.awt.Color(255, 255, 255));
        Item6.setMinimumSize(new java.awt.Dimension(178, 157));

        imgItem6.setMaximumSize(new java.awt.Dimension(100, 63));
        imgItem6.setMinimumSize(new java.awt.Dimension(100, 63));
        imgItem6.setPreferredSize(new java.awt.Dimension(100, 63));

        lbHPrice6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbHPrice6.setText("Giá:");

        lbNameItem6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbNameItem6.setText("Vans FOG");

        lbPriceItem6.setText("Giá");

        lbHAmount6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbHAmount6.setText("Số lượng:");

        lbAmountItem6.setText("Số lượng");

        btnAdd6.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Downloads\\add-to-cart (1).png")); // NOI18N
        btnAdd6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdd6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Item6Layout = new javax.swing.GroupLayout(Item6);
        Item6.setLayout(Item6Layout);
        Item6Layout.setHorizontalGroup(
            Item6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Item6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Item6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Item6Layout.createSequentialGroup()
                        .addComponent(lbHPrice6)
                        .addGap(49, 49, 49)
                        .addComponent(lbPriceItem6, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(lbNameItem6)
                    .addGroup(Item6Layout.createSequentialGroup()
                        .addComponent(lbHAmount6)
                        .addGap(18, 18, 18)
                        .addComponent(lbAmountItem6, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(Item6Layout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addComponent(imgItem6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnAdd6)
                .addGap(12, 12, 12))
        );
        Item6Layout.setVerticalGroup(
            Item6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Item6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Item6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(imgItem6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdd6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbNameItem6)
                .addGap(8, 8, 8)
                .addGroup(Item6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbHPrice6)
                    .addComponent(lbPriceItem6))
                .addGap(8, 8, 8)
                .addGroup(Item6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbAmountItem6)
                    .addComponent(lbHAmount6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnProfile.setText("Thông tin cá nhân");
        btnProfile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Item4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Item5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Item6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Item1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Item2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Item3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(tfSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnShowAll)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnProfile)))
                .addGap(30, 30, 30))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSearch, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnCart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfSearch)
                    .addComponent(btnShowAll, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnProfile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Item1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Item2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Item3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Item4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Item5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Item6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfSearchActionPerformed

    }//GEN-LAST:event_tfSearchActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
//		System.out.println(getUsername()); // username của form Login
		lbNameItem1.setText(listItemName.get(0));
		lbNameItem2.setText(listItemName.get(1));
		lbNameItem3.setText(listItemName.get(2));
		lbNameItem4.setText(listItemName.get(3));
		lbNameItem5.setText(listItemName.get(4));
		lbNameItem6.setText(listItemName.get(5));

		lbPriceItem1.setText(listPrice.get(0) + "");
		lbPriceItem2.setText(listPrice.get(1) + "");
		lbPriceItem3.setText(listPrice.get(2) + "");
		lbPriceItem4.setText(listPrice.get(3) + "");
		lbPriceItem5.setText(listPrice.get(4) + "");
		lbPriceItem6.setText(listPrice.get(5) + "");

		lbAmountItem1.setText(listAmount.get(0) + "");
		lbAmountItem2.setText(listAmount.get(1) + "");
		lbAmountItem3.setText(listAmount.get(2) + "");
		lbAmountItem4.setText(listAmount.get(3) + "");
		lbAmountItem5.setText(listAmount.get(4) + "");
		lbAmountItem6.setText(listAmount.get(5) + "");

		ImageIcon img1 = new ImageIcon("D:\\NetBeans\\BTL_JAVA\\BTL_Java\\src\\image\\yeezy1_resize.png");
		imgItem1.setIcon(img1);
		ImageIcon img2 = new ImageIcon("D:\\NetBeans\\BTL_JAVA\\BTL_Java\\src\\image\\air1.png");
		imgItem2.setIcon(img2);
		ImageIcon img3 = new ImageIcon("D:\\NetBeans\\BTL_JAVA\\BTL_Java\\src\\image\\jodan1_resize.png");
		imgItem3.setIcon(img3);
		ImageIcon img4 = new ImageIcon("D:\\NetBeans\\BTL_JAVA\\BTL_Java\\src\\image\\jordan_travis.png");
		imgItem4.setIcon(img4);
		ImageIcon img5 = new ImageIcon("D:\\NetBeans\\BTL_JAVA\\BTL_Java\\src\\image\\jordan4_black.png");
		imgItem5.setIcon(img5);
		ImageIcon img6 = new ImageIcon("D:\\NetBeans\\BTL_JAVA\\BTL_Java\\src\\image\\vans.png");
		imgItem6.setIcon(img6);
    }//GEN-LAST:event_formWindowOpened

    private void btnCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCartActionPerformed
//		System.out.println(countItem1);
//		System.out.println(countItem2);
//		System.out.println(countItem3);
//		System.out.println(countItem4);
//		System.out.println(countItem5);
//		System.out.println(countItem6);

		int price;
		int money;
		Vector itemAdded;
		ArrayList<Integer> listItemAmount = new ArrayList<>();
//		listAmount
		
		if (countItem1 > 0) {
			if(countItem1 > listAmount.get(0)) {
				JOptionPane.showMessageDialog(this, "Số lượng sản phẩm vượt quá số lượng trong kho");
				countItem1 = 0;
			} else {
				JOptionPane.showMessageDialog(this, "Đã thêm sản phẩm vào giỏ hàng");
				itemAdded = new Vector();
				price = Integer.parseInt(lbPriceItem1.getText());
				money = price * countItem1;
				itemAdded.add(lbNameItem1.getText());
				itemAdded.add(countItem1);
				itemAdded.add(price);
				itemAdded.add(money);
				listTtemAdded.add(itemAdded);
			}
		}

		if (countItem2 > 0) {
			if(countItem2 > listAmount.get(1)) {
				JOptionPane.showMessageDialog(this, "Số lượng sản phẩm vượt quá số lượng trong kho");
				countItem2 = 0;
			} else {
				JOptionPane.showMessageDialog(this, "Đã thêm sản phẩm vào giỏ hàng");
				itemAdded = new Vector();
				price = Integer.parseInt(lbPriceItem2.getText());
				money = price * countItem2;
				itemAdded.add(lbNameItem2.getText());
				itemAdded.add(countItem2);
				itemAdded.add(price);
				itemAdded.add(money);
				listTtemAdded.add(itemAdded);
			}
		}

		if (countItem3 > 0) {
			if(countItem3 > listAmount.get(2)) {
				JOptionPane.showMessageDialog(this, "Số lượng sản phẩm vượt quá số lượng trong kho");
				countItem3 = 0;
			} else {
				JOptionPane.showMessageDialog(this, "Đã thêm sản phẩm vào giỏ hàng");
				itemAdded = new Vector();
				price = Integer.parseInt(lbPriceItem3.getText());
				money = price * countItem3;
				itemAdded.add(lbNameItem3.getText());
				itemAdded.add(countItem3);
				itemAdded.add(price);
				itemAdded.add(money);
				listTtemAdded.add(itemAdded);
			}
		}

		if (countItem4 > 0) {
			if(countItem4 > listAmount.get(3)) {
				JOptionPane.showMessageDialog(this, "Số lượng sản phẩm vượt quá số lượng trong kho");
				countItem4 = 0;
				System.out.println("countItem4: " + countItem4);
				System.out.println("listAmount: " + listAmount);
			} else {
				System.out.println("countItem4: " + countItem4);
				JOptionPane.showMessageDialog(this, "Đã thêm sản phẩm vào giỏ hàng");
				itemAdded = new Vector();
				price = Integer.parseInt(lbPriceItem4.getText());
				money = price * countItem4;
				itemAdded.add(lbNameItem4.getText());
				itemAdded.add(countItem4);
				itemAdded.add(price);
				itemAdded.add(money);
				listTtemAdded.add(itemAdded);
			}
		}

		if (countItem5 > 0) {
			if(countItem5 > listAmount.get(4)) {
				JOptionPane.showMessageDialog(this, "Số lượng sản phẩm vượt quá số lượng trong kho");
				countItem5 = 0;
				listAmount.set(4,0);
			} else {
				JOptionPane.showMessageDialog(this, "Đã thêm sản phẩm vào giỏ hàng");
				itemAdded = new Vector();
				price = Integer.parseInt(lbPriceItem5.getText());
				money = price * countItem5;
				itemAdded.add(lbNameItem5.getText());
				itemAdded.add(countItem5);
				itemAdded.add(price);
				itemAdded.add(money);
				listTtemAdded.add(itemAdded);
			}
		}

		if (countItem6 > 0) {
			if(countItem6 > listAmount.get(5)) {
				JOptionPane.showMessageDialog(this, "Số lượng sản phẩm vượt quá số lượng trong kho");
				countItem6 = 0;
			} else {
				JOptionPane.showMessageDialog(this, "Đã thêm sản phẩm vào giỏ hàng");
				itemAdded = new Vector();
				price = Integer.parseInt(lbPriceItem6.getText());
				money = price * countItem6;
				itemAdded.add(lbNameItem6.getText());
				itemAdded.add(countItem6);
				itemAdded.add(price);
				itemAdded.add(money);
				listTtemAdded.add(itemAdded);
			}
		}
		
		if(countItem1 <= listAmount.get(0)) {
			if(countItem2 <= listAmount.get(1)) {
				if(countItem3 <= listAmount.get(2)) {
					if(countItem4 <= listAmount.get(3)) {
						if(countItem5 <= listAmount.get(4)) {
							if(countItem6 <= listAmount.get(5)) {
								frmCart windowCart = new frmCart();
								windowCart.setVisible(true);
							}
						}
					}
				}
			}
		}
    }//GEN-LAST:event_btnCartActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
//		countClicked++;
		String findingName = tfSearch.getText().toLowerCase();
		Boolean verify = false; // verify: Dùng để check xem có sản phẩm đang tìm kiếm không

		if (findingName.isEmpty()) {
			JOptionPane.showMessageDialog(this, "Hãy nhập tên sản phẩm");
		} else {
			for (int i = 0; i < listItemNameLowerCase.size(); i++) {
				if (listItemNameLowerCase.get(i).contains(findingName)) {
					verify = true;
					result.add(listItemName.get(i));
				}
			}
		}
		if (verify) {
			JOptionPane.showMessageDialog(this, "Đã tìm thấy sản phẩm");
			setResultVector(result);
			windowSearch = new frmSearch();
			windowSearch.setVisible(true);
			// Nếu click button Search lần đầu sẽ tạo mới frmSearch
//			if(countClicked == 1) {
//				
//			} else {
//				windowSearch.setVisible(true);
//			}

		} else {
			JOptionPane.showMessageDialog(this, "Không tìm thấy sản phẩm");
		}
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnShowAllActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowAllActionPerformed
		frmAllProductClient windowAllProductClient = new frmAllProductClient();
		windowAllProductClient.setVisible(true);
    }//GEN-LAST:event_btnShowAllActionPerformed

    private void btnProfileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfileActionPerformed
		frmProfile windowProfile = new frmProfile();
		windowProfile.setVisible(true);
    }//GEN-LAST:event_btnProfileActionPerformed

    private void btnAdd4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdd4ActionPerformed
		// TODO add your handling code here:
		countItem4 += 1;
		JOptionPane.showMessageDialog(this,
			"Đã thêm sản phẩm vào giỏ hàng");
    }//GEN-LAST:event_btnAdd4ActionPerformed

    private void btnAdd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdd1ActionPerformed
		// TODO add your handling code here:
		countItem1 += 1;
		JOptionPane.showMessageDialog(this,
			"Đã thêm sản phẩm vào giỏ hàng");
    }//GEN-LAST:event_btnAdd1ActionPerformed

    private void tfSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfSearchKeyPressed
		// TODO add your handling code here:
    }//GEN-LAST:event_tfSearchKeyPressed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
//		this.dispose();
    }//GEN-LAST:event_formWindowClosing

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
//        frmLogin.frame.dispose();
    }//GEN-LAST:event_formWindowClosed

    private void btnAdd2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdd2ActionPerformed
		// TODO add your handling code here:
		countItem2 += 1;
		JOptionPane.showMessageDialog(this,
			"Đã thêm sản phẩm vào giỏ hàng");
    }//GEN-LAST:event_btnAdd2ActionPerformed

    private void btnAdd3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdd3ActionPerformed
		// TODO add your handling code here:
		countItem3 += 1;
		JOptionPane.showMessageDialog(this,
			"Đã thêm sản phẩm vào giỏ hàng");
    }//GEN-LAST:event_btnAdd3ActionPerformed

    private void btnAdd5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdd5ActionPerformed
		// TODO add your handling code here:
		countItem5 += 1;
		JOptionPane.showMessageDialog(this,
			"Đã thêm sản phẩm vào giỏ hàng");
    }//GEN-LAST:event_btnAdd5ActionPerformed

    private void btnAdd6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdd6ActionPerformed
		// TODO add your handling code here:
		countItem6 += 1;
		JOptionPane.showMessageDialog(this,
			"Đã thêm sản phẩm vào giỏ hàng");
    }//GEN-LAST:event_btnAdd6ActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(frmItemClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(frmItemClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(frmItemClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(frmItemClient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				try {
					new frmItemClient().setVisible(true);
				} catch (SQLException ex) {
					Logger.getLogger(frmItemClient.class.getName()).log(Level.SEVERE, null, ex);
				}
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Item1;
    private javax.swing.JPanel Item2;
    private javax.swing.JPanel Item3;
    private javax.swing.JPanel Item4;
    private javax.swing.JPanel Item5;
    private javax.swing.JPanel Item6;
    private javax.swing.JButton btnAdd1;
    private javax.swing.JButton btnAdd2;
    private javax.swing.JButton btnAdd3;
    private javax.swing.JButton btnAdd4;
    private javax.swing.JButton btnAdd5;
    private javax.swing.JButton btnAdd6;
    private javax.swing.JButton btnCart;
    private javax.swing.JButton btnProfile;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnShowAll;
    private javax.swing.JLabel imgItem1;
    private javax.swing.JLabel imgItem2;
    private javax.swing.JLabel imgItem3;
    private javax.swing.JLabel imgItem4;
    private javax.swing.JLabel imgItem5;
    private javax.swing.JLabel imgItem6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbAmountItem1;
    private javax.swing.JLabel lbAmountItem2;
    private javax.swing.JLabel lbAmountItem3;
    private javax.swing.JLabel lbAmountItem4;
    private javax.swing.JLabel lbAmountItem5;
    private javax.swing.JLabel lbAmountItem6;
    private javax.swing.JLabel lbHAmount1;
    private javax.swing.JLabel lbHAmount2;
    private javax.swing.JLabel lbHAmount3;
    private javax.swing.JLabel lbHAmount4;
    private javax.swing.JLabel lbHAmount5;
    private javax.swing.JLabel lbHAmount6;
    private javax.swing.JLabel lbHPrice1;
    private javax.swing.JLabel lbHPrice2;
    private javax.swing.JLabel lbHPrice3;
    private javax.swing.JLabel lbHPrice4;
    private javax.swing.JLabel lbHPrice5;
    private javax.swing.JLabel lbHPrice6;
    private javax.swing.JLabel lbNameItem1;
    private javax.swing.JLabel lbNameItem2;
    private javax.swing.JLabel lbNameItem3;
    private javax.swing.JLabel lbNameItem4;
    private javax.swing.JLabel lbNameItem5;
    private javax.swing.JLabel lbNameItem6;
    private javax.swing.JLabel lbPriceItem1;
    private javax.swing.JLabel lbPriceItem2;
    private javax.swing.JLabel lbPriceItem3;
    private javax.swing.JLabel lbPriceItem4;
    private javax.swing.JLabel lbPriceItem5;
    private javax.swing.JLabel lbPriceItem6;
    private javax.swing.JTextField tfSearch;
    // End of variables declaration//GEN-END:variables
}
