/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form;

import DataBaseConnection.DataBaseConnection;
import static form.frmItemClient.getResultVector;
import static form.frmItemClient.result;
import java.sql.PreparedStatement;
import javax.swing.*;
import java.sql.ResultSet;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author NguyenCongHoan
 */
public class frmSearch extends javax.swing.JFrame {

	static String itemName;
	int itemPrice;
	int itemAmount;
	String itemLinkImage = "";
	// Khi click btnSearch trong frmItemClient
	// thì Vector result sẽ được thêm dữ liệu sau mỗi lần click
	// để Vector result không ghi thêm dữ liệu
	// thì cần phải xóa tất cả các phần tử sau khi đóng frmSearch
	static Vector listItem = getResultVector();
	Vector data = new Vector();

	// Danh sách sản phẩm đã được thêm vào giỏ hàng
	static Vector listTtemAdded = new Vector();

	// Danh sách số lượng của từng sản phẩm
	static ArrayList<Integer> listItemAmount = new ArrayList<>();
	int selectedRow;

	// Số lượng sản phẩm trong bảng
	static int itemInTable = listItem.size();

	// Đếm số lượng của từng sản phẩm trong bảng khi click nút Add to card
	static int[] itemCount = new int[itemInTable];
	static Vector vListPriceItem = new Vector(); // vector ListPriceItem

	public frmSearch() {
		initComponents();
	}

	void setItemName(String itemName) {
		this.itemName = itemName;
	}

	public static String getItemName() {
		return itemName;
	}

//	void setListItemAddedd(Vector listTtemAdded) {
//		this.listTtemAdded = listTtemAdded;
//	}
//	
//	public static Vector<String> getListItemAddedd() {
//		return listTtemAdded;
//	}
//	 Hàm trả về danh sách sản phẩm đã được thêm vào giỏ hàng 
//	public static Vector<Vector> createListTtemAdded() {
//		Vector<Vector> listTtemAdded = new Vector();
//		try {	
//			for(int i = 0; i < listItem.size(); i++) {
//				Vector itemAdded = new Vector();
//				if(itemCount[i] > 0) {
//					itemAdded.add(listItem.get(i));
//					itemAdded.add(itemCount[i]);
//					itemAdded.add(vListPriceItem.get(i));
//					int totolMoney = itemCount[i] *(int) vListPriceItem.get(i);
//					itemAdded.add(totolMoney);
//				} else {
//					continue;
//				}
//					listTtemAdded.add(itemAdded);
//			}		
//		} catch (Exception ex) {
//			ex.printStackTrace();
//		}
//		System.out.println("ListItemAdded: " + listTtemAdded);
//		return listTtemAdded;
//	}
	private void displayDetails(int selectIndex) {
		Vector vSelectedRow = (Vector) data.get(selectIndex);
		String itemName = (String) vSelectedRow.get(0);
		lbItemName.setText(itemName);
	}

	/**
	 * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAddItem = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbItem = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        lbHNameItem = new javax.swing.JLabel();
        lbHPrice = new javax.swing.JLabel();
        lbHPrice1 = new javax.swing.JLabel();
        imgItem = new javax.swing.JLabel();
        btnAddToCart = new javax.swing.JButton();
        lbItemName = new javax.swing.JLabel();
        lbItemPrice = new javax.swing.JLabel();
        lbItemAmount = new javax.swing.JLabel();

        btnAddItem.setBackground(new java.awt.Color(153, 153, 153));
        btnAddItem.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAddItem.setText("Thêm vào giỏ hàng");
        btnAddItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddItemActionPerformed(evt);
            }
        });

        setTitle("WindowResult");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 0, 0));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Kết quả tìm kiếm");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 49, Short.MAX_VALUE)
        );

        jScrollPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jScrollPane1.setPreferredSize(new java.awt.Dimension(289, 402));

        tbItem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Tên sản phẩm"
            }
        ));
        tbItem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbItemMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbItem);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Chi tiết sản phẩm", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        lbHNameItem.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbHNameItem.setText("Tên sản phẩm:");

        lbHPrice.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbHPrice.setText("Giá tiền:");

        lbHPrice1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lbHPrice1.setText("Số lượng trong kho:");

        imgItem.setMaximumSize(new java.awt.Dimension(100, 63));
        imgItem.setMinimumSize(new java.awt.Dimension(100, 63));
        imgItem.setPreferredSize(new java.awt.Dimension(100, 63));

        btnAddToCart.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnAddToCart.setText("Add to card");
        btnAddToCart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddToCartActionPerformed(evt);
            }
        });

        lbItemName.setText("lbItemName");

        lbItemPrice.setText("lbItemPrice");

        lbItemAmount.setText("lbItemAmount");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lbHPrice1)
                        .addGap(12, 12, 12)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnAddToCart)
                            .addComponent(lbItemAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lbHNameItem)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbItemName, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lbHPrice)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbItemPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60)
                        .addComponent(imgItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(47, 47, 47))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbHNameItem)
                    .addComponent(lbItemName, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbHPrice)
                            .addComponent(lbItemPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(imgItem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbHPrice1)
                    .addComponent(lbItemAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(btnAddToCart)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddItemActionPerformed
		// TODO add your handling code here:
    }//GEN-LAST:event_btnAddItemActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
		try {
			Vector columnName = new Vector();
			columnName.add("Tên sản phẩm");
			// DefaultTableModel là Vector 2 chiều
			// DefautTableModel có 2 tham số
			// rowCount: số dòng
			// columnCount: số cột
			DefaultTableModel dataTable = new DefaultTableModel(data, columnName);			// Mỗi vRow là 1 dòng trong Jtable
			for (int i = 0; i < listItem.size(); i++) {
				Vector vRow = new Vector();
				vRow.add(listItem.get(i));
				data.add(vRow);
			}
			dataTable = new DefaultTableModel(data, columnName);
			tbItem.setModel(dataTable);
		} catch (Exception ex) {
			ex.printStackTrace();
		}

		Connection cnt = null;
		PreparedStatement stm = null;
		try {
			cnt = DataBaseConnection.getConnection();
			String sql = "SELECT so_luong, gia FROM tbsanpham WHERE ten_san_pham = ?";
			stm = cnt.prepareStatement(sql);
			for (int i = 0; i < listItem.size(); i++) {
				stm.setString(1, (String) listItem.get(i));
				ResultSet rs = stm.executeQuery();

				while (rs.next()) {
					itemPrice = rs.getInt("gia");
					vListPriceItem.add(itemPrice);
					listItemAmount.add(rs.getInt("so_luong"));
				}
			}

		} catch (ClassNotFoundException ex) {
			Logger.getLogger(frmItemClient.class.getName()).log(Level.SEVERE, null, ex);
		} catch (SQLException ex) {
			Logger.getLogger(frmSearch.class.getName()).log(Level.SEVERE, null, ex);
		} finally {
			try {
				if (stm != null) {
					stm.close();
				}

				if (cnt != null) {
					cnt.close();
				}

			} catch (SQLException ex) {
				Logger.getLogger(frmLogin.class.getName()).log(Level.SEVERE, null, ex);
			}
		}
    }//GEN-LAST:event_formWindowOpened

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
//		System.out.println(dataTable.getRowCount());
//		dataTable.setRowCount(0);
//		System.out.println(dataTable.getRowCount());
    }//GEN-LAST:event_formWindowClosed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
//		try {	
//			for(int i = 0; i < listItem.size(); i++) {
//				Vector itemAdded = new Vector();
//				if(itemCount[i] > 0) {
//					itemAdded.add(listItem.get(i));
//					itemAdded.add(itemCount[i]);
//					itemAdded.add(vListPriceItem.get(i));
//				} else {
//					continue;
//				}
//					listTtemAdded.add(itemAdded);
//			}		
//		} catch (Exception ex) {
//			ex.printStackTrace();
//		}
//		
//		System.out.println("ListItemAdded: " + createListTtemAdded());
//		System.out.println(vListPriceItem);
//		System.out.println(listItem);
		try {
			for (int i = 0; i < listItem.size(); i++) {
				Vector itemAdded = new Vector();
				if (itemCount[i] > 0) {
					itemAdded.add(listItem.get(i));
					itemAdded.add(itemCount[i]);
					itemAdded.add(vListPriceItem.get(i));
					int totolMoney = itemCount[i] * (int) vListPriceItem.get(i);
					itemAdded.add(totolMoney);
				} else {
					continue;
				}
				listTtemAdded.add(itemAdded);
			}
		} catch (Exception ex) {
			ex.printStackTrace();
		}

		try {
			frmItemClient.listTtemAdded = listTtemAdded;
		} catch (Exception ex) {
			ex.printStackTrace();
		}

//		System.out.println("frmItemClient.listTtemAdded: " + frmItemClient.listTtemAdded);
//		System.out.println("listTtemAdded: " + listTtemAdded);
//		System.out.println("Size: " + frmItemClient.listTtemAdded.size());

		// Đặt lại giá trị của tất cả phẩm tử trong itemCount = 0
//		System.out.println("So luong san pham");
		for (int i = 0; i < listItem.size(); i++) {
//			System.out.println(itemCount[i]);
			itemCount[i] = 0;
		}
		// Xóa tất cả các phần tử trong listItem 
		// Để khi mở frmSearch, listItem sẽ được làm mới
		listItem.clear();
    }//GEN-LAST:event_formWindowClosing

	// Khi click chuột vào 1 dòng, sẽ hiển thị thông tin của dòng đó
    private void tbItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbItemMouseClicked
		selectedRow = tbItem.getSelectedRow();
		displayDetails(selectedRow);
//		System.out.println("selectedRow: " + selectedRow);
		itemName = lbItemName.getText();
		Connection cnt = null;
		PreparedStatement stm = null;
		try {
			cnt = DataBaseConnection.getConnection();
			String sql = "SELECT gia, so_luong, link_image FROM tbsanpham WHERE ten_san_pham = ?";
			stm = cnt.prepareStatement(sql);
			stm.setString(1, itemName);
			ResultSet rs = stm.executeQuery();

			while (rs.next()) {
				itemPrice = rs.getInt("gia");
				itemAmount = rs.getInt("so_luong");
				itemLinkImage = rs.getString("link_image");
			}

		} catch (ClassNotFoundException ex) {
			Logger.getLogger(frmItemClient.class.getName()).log(Level.SEVERE, null, ex);
		} catch (SQLException ex) {
			Logger.getLogger(frmSearch.class.getName()).log(Level.SEVERE, null, ex);
		} finally {
			try {
				if (stm != null) {
					stm.close();
				}

				if (cnt != null) {
					cnt.close();
				}

			} catch (SQLException ex) {
				Logger.getLogger(frmLogin.class.getName()).log(Level.SEVERE, null, ex);
			}
		}
		lbItemPrice.setText(itemPrice + "");
		lbItemAmount.setText(itemAmount + "");
		ImageIcon img = new ImageIcon(itemLinkImage);
		imgItem.setIcon(img);
//		lbItemPrice.setText(itemPrice);
    }//GEN-LAST:event_tbItemMouseClicked

	// Button Add To Card
    private void btnAddToCartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddToCartActionPerformed
		// TODO add your handling code here:
//		setItemName(itemName);
//		frmCart windowCart = new frmCart();
//		windowCart.setVisible(true);
		JOptionPane.showMessageDialog(this, "Đã thêm sản phẩm vào giỏ hàng");
		// Mỗi lần click nút Add to cart thì sẽ tăng số sản phẩm của dòng được chọn
		// Lên 1 đơn vị
		itemCount[selectedRow] += 1;
		if (itemCount[selectedRow] > itemAmount) {
			JOptionPane.showMessageDialog(this, "Số lượng sản phẩm đã vượt quá số lượng trong giỏ hàng");
			itemCount[selectedRow] = itemAmount;
		}
//		System.out.println(itemCount[selectedRow]);
    }//GEN-LAST:event_btnAddToCartActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(frmSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(frmSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(frmSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(frmSearch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new frmSearch().setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddItem;
    private javax.swing.JButton btnAddToCart;
    private javax.swing.JLabel imgItem;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbHNameItem;
    private javax.swing.JLabel lbHPrice;
    private javax.swing.JLabel lbHPrice1;
    private javax.swing.JLabel lbItemAmount;
    private javax.swing.JLabel lbItemName;
    private javax.swing.JLabel lbItemPrice;
    private javax.swing.JTable tbItem;
    // End of variables declaration//GEN-END:variables
}
